# Generated by Django 5.2 on 2025-04-13 08:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Sensor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='Tên cảm biến')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Mô tả')),
                ('location', models.CharField(blank=True, max_length=200, null=True, verbose_name='Vị trí')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Thời điểm tạo')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Thời điểm cập nhật')),
            ],
            options={
                'verbose_name': 'Cảm biến',
                'verbose_name_plural': 'Các cảm biến',
            },
        ),
    ]
