sonar.projectKey=CollinsD61_web_project
sonar.organization=collinsd61
sonar.sources=FE,BE_nodejs
sonar.projectName=web_project

# Node.js Backend
sonar.javascript.lcov.reportPaths=BE_nodejs/coverage/lcov.info
sonar.exclusions=**/node_modules/**,**/dist/**,**/build/**,**/coverage/**

# Frontend
sonar.typescript.lcov.reportPaths=FE/coverage/lcov.info

# Exclude old Django backend from scanning
sonar.exclusions=BE/**,**/migrations/**,**/__pycache__/**
