# Generated by Django 5.2 on 2025-04-13 08:32

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('sensors', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SensorData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Thời điểm')),
                ('light_value', models.FloatField(blank=True, null=True, verbose_name='Giá trị ánh sáng')),
                ('temperature', models.FloatField(blank=True, null=True, verbose_name='Nhiệt độ (°C)')),
                ('humidity', models.FloatField(blank=True, null=True, verbose_name='Độ ẩm (%)')),
                ('sensor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='data_points', to='sensors.sensor', verbose_name='Cảm biến')),
            ],
            options={
                'verbose_name': 'Dữ liệu cảm biến',
                'verbose_name_plural': 'Dữ liệu các cảm biến',
                'ordering': ['-timestamp'],
            },
        ),
    ]
