name: Deploy to VPS

on:
  push:
    branches:
      - master   # Đổi thành branch bạn muốn auto deploy, ví dụ: main nếu bạn dùng main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup SSH key
        uses: webfactory/ssh-agent@v0.8.0
        with:
          ssh-private-key: ${{ secrets.SSH_KEY }}

      - name: Prepare project folder on VPS
        run: |
          ssh -o StrictHostKeyChecking=no ${{ secrets.SSH_USER }}@222.255.238.187 "mkdir -p /root/web_project"

      - name: Copy entire codebase to VPS via rsync
        run: |
          rsync -avz --delete \
            -e "ssh -o StrictHostKeyChecking=no" \
            ./ ${{ secrets.SSH_USER }}@222.255.238.187:/root/web_project/

      - name: SSH and deploy Docker Compose
        run: |
          ssh -o StrictHostKeyChecking=no ${{ secrets.SSH_USER }}@222.255.238.187 "
            cd /root/web_project &&
            docker compose down || true &&
            docker compose up -d --build
            docker image prune -af

          "
